export const symptomData = `
0	Fungal infection	itching	skin_rash	nodal_skin_eruptions	dischromic _patches
1	Fungal infection	skin_rash	nodal_skin_eruptions	dischromic _patches
2	Fungal infection	itching	nodal_skin_eruptions	dischromic _patches
3	Fungal infection	itching	skin_rash	dischromic _patches
4	Fungal infection	itching	skin_rash	nodal_skin_eruptions
`;

export const allSymptoms = [
    "itching",
    "skin_rash",
    "nodal_skin_eruptions",
    "dischromic _patches",
    "continuous_sneezing",
    "shivering",
    "chills",
    "watering_from_eyes",
    "stomach_pain",
    "acidity",
    "ulcers_on_tongue",
    "vomiting",
    "cough",
    "chest_pain",
    "yellowish_skin",
    "nausea",
    "loss_of_appetite",
    "abdominal_pain",
    "yellowing_of_eyes",
    "burning_micturition",
    "spotting_ urination",
    "passage_of_gases",
    "internal_itching",
    "indigestion",
    "muscle_wasting",
    "patches_in_throat",
    "high_fever",
    "extra_marital_contacts",
    "fatigue",
    "weight_loss",
    "restlessness",
    "lethargy",
    "irregular_sugar_level",
    "blurred_and_distorted_vision",
    "obesity",
    "excessive_hunger",
    "increased_appetite",
    "polyuria",
    "family_history",
    "mucoid_sputum",
    "rusty_sputum",
    "lack_of_concentration",
    "visual_disturbances",
    "receiving_blood_transfusion",
    "receiving_unsterile_injections",
    "coma",
    "stomach_bleeding",
    "distention_of_abdomen",
    "history_of_alcohol_consumption",
    "fluid_overload",
    "blood_in_sputum",
    "prominent_veins_on_calf",
    "palpitations",
    "painful_walking",
    "pus_filled_pimples",
    "blackheads",
    "scurring",
    "skin_peeling",
    "silver_like_dusting",
    "small_dents_in_nails",
    "inflammatory_nails",
    "blister",
    "red_sore_around_nose",
    "yellow_crust_ooze"
];
